export const routePreloaders = {
  login: () => import('@/features/auth/pages/LoginPage'),
  dashboard: () => import('@/features/dashboard/pages/DashboardPage'),
  agenda: () => import('@/features/agenda/pages/AgendaPage'),
  students: () => import('@/features/students/pages/StudentsPage'),
  guardians: () => import('@/features/guardians/pages/GuardiansPage'),
  classes: () => import('@/features/classes/pages/ClassesPage'),
  attendance: () => import('@/features/attendance/pages/AttendancePage'),
  billing: () => import('@/features/billing/pages/BillingPage'),
  finance: () => import('@/features/finance/pages/FinancePage'),
  events: () => import('@/features/events/pages/EventsPage'),
  materials: () => import('@/features/materials/pages/MaterialsPage'),
  ideas: () => import('@/features/ideas/pages/IdeasPage'),
  reports: () => import('@/features/reports/pages/ReportsPage'),
  settings: () => import('@/features/settings/pages/SettingsPage'),
}
